version: '3.9'

services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: cartservice-postgres-db
    ports:
      - "5432:5432"
    environment:
      "POSTGRES_DB": "cartservice"
      "POSTGRES_USER": "postgres"
      "POSTGRES_PASSWORD": "postgres"