/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package by.jenka.rss;


import by.jenka.rss.verification.ClasspathResourceChecker;

public class TaskRunner {


    public static void main(String[] args) {
        System.out.println("-------------   Start app");
        new ClasspathResourceChecker().run();
        System.out.println("---------------  End app");
    }
}
